# Generated by Django 3.2.9 on 2021-12-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211207_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoproduto',
            name='descricao',
            field=models.CharField(max_length=250, verbose_name='Descrição'),
        ),
    ]
